// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpzcV8FxFz2Nzq76zwu_YanbsiHFgIBw',
    appId: '1:267785610986:web:4ad9c3869d10321a4e1993',
    messagingSenderId: '267785610986',
    projectId: 'ecommerce-519ae',
    authDomain: 'ecommerce-519ae.firebaseapp.com',
    storageBucket: 'ecommerce-519ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2KoTgQnKNXxJ1x8gvSA3ZUfHx-ky7KA',
    appId: '1:267785610986:android:eae63c52d2f659794e1993',
    messagingSenderId: '267785610986',
    projectId: 'ecommerce-519ae',
    storageBucket: 'ecommerce-519ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBKNVJFz3lt2ZtXaqLGPlXABLfedxln4',
    appId: '1:267785610986:ios:c69d7b7304ac2a994e1993',
    messagingSenderId: '267785610986',
    projectId: 'ecommerce-519ae',
    storageBucket: 'ecommerce-519ae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqBKNVJFz3lt2ZtXaqLGPlXABLfedxln4',
    appId: '1:267785610986:ios:c69d7b7304ac2a994e1993',
    messagingSenderId: '267785610986',
    projectId: 'ecommerce-519ae',
    storageBucket: 'ecommerce-519ae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDpzcV8FxFz2Nzq76zwu_YanbsiHFgIBw',
    appId: '1:267785610986:web:dd32fa3ef0d357254e1993',
    messagingSenderId: '267785610986',
    projectId: 'ecommerce-519ae',
    authDomain: 'ecommerce-519ae.firebaseapp.com',
    storageBucket: 'ecommerce-519ae.firebasestorage.app',
  );
}
